package org.jlobato.gpro.dao.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jlobato.gpro.dao.mybatis.model.ManagerHistory;
import org.jlobato.gpro.dao.mybatis.model.ManagerHistoryExample;

public interface ManagerHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    long countByExample(ManagerHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int deleteByExample(ManagerHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int deleteByPrimaryKey(Integer idManagerHistory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int insert(ManagerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int insertSelective(ManagerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    List<ManagerHistory> selectByExample(ManagerHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    ManagerHistory selectByPrimaryKey(Integer idManagerHistory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int updateByExampleSelective(@Param("record") ManagerHistory record, @Param("example") ManagerHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int updateByExample(@Param("record") ManagerHistory record, @Param("example") ManagerHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int updateByPrimaryKeySelective(ManagerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_history
     *
     * @mbg.generated Sun Dec 09 12:52:58 CET 2018
     */
    int updateByPrimaryKey(ManagerHistory record);
}