package org.jlobato.gpro.dao.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jlobato.gpro.dao.mybatis.model.ManagerTeamHistory;
import org.jlobato.gpro.dao.mybatis.model.ManagerTeamHistoryExample;

public interface ManagerTeamHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    long countByExample(ManagerTeamHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int deleteByExample(ManagerTeamHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int deleteByPrimaryKey(Integer idManagerTeamHistory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int insert(ManagerTeamHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int insertSelective(ManagerTeamHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    List<ManagerTeamHistory> selectByExample(ManagerTeamHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    ManagerTeamHistory selectByPrimaryKey(Integer idManagerTeamHistory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int updateByExampleSelective(@Param("record") ManagerTeamHistory record, @Param("example") ManagerTeamHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int updateByExample(@Param("record") ManagerTeamHistory record, @Param("example") ManagerTeamHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int updateByPrimaryKeySelective(ManagerTeamHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_team_history
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    int updateByPrimaryKey(ManagerTeamHistory record);
}