package org.jlobato.gpro.dao.mybatis.model;

import java.io.Serializable;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    private Short idCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.code_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    private String codeCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.description_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    private String descriptionCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.lvl_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    private Short lvlCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id_category
     *
     * @return the value of category.id_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Short getIdCategory() {
        return idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Category withIdCategory(Short idCategory) {
        this.setIdCategory(idCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id_category
     *
     * @param idCategory the value for category.id_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public void setIdCategory(Short idCategory) {
        this.idCategory = idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.code_category
     *
     * @return the value of category.code_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public String getCodeCategory() {
        return codeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Category withCodeCategory(String codeCategory) {
        this.setCodeCategory(codeCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.code_category
     *
     * @param codeCategory the value for category.code_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public void setCodeCategory(String codeCategory) {
        this.codeCategory = codeCategory == null ? null : codeCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description_category
     *
     * @return the value of category.description_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public String getDescriptionCategory() {
        return descriptionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Category withDescriptionCategory(String descriptionCategory) {
        this.setDescriptionCategory(descriptionCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description_category
     *
     * @param descriptionCategory the value for category.description_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public void setDescriptionCategory(String descriptionCategory) {
        this.descriptionCategory = descriptionCategory == null ? null : descriptionCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.lvl_category
     *
     * @return the value of category.lvl_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Short getLvlCategory() {
        return lvlCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public Category withLvlCategory(Short lvlCategory) {
        this.setLvlCategory(lvlCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.lvl_category
     *
     * @param lvlCategory the value for category.lvl_category
     *
     * @mbg.generated Sat May 06 16:20:58 CEST 2017
     */
    public void setLvlCategory(Short lvlCategory) {
        this.lvlCategory = lvlCategory;
    }
}