package org.jlobato.gpro.dao.mybatis.model;

import java.io.Serializable;

public class Weather implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.id_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    private Integer idWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.cod_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    private String codWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.description_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    private String descriptionWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.img_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    private byte[] imgWeather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.id_weather
     *
     * @return the value of weather.id_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public Integer getIdWeather() {
        return idWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public Weather withIdWeather(Integer idWeather) {
        this.setIdWeather(idWeather);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.id_weather
     *
     * @param idWeather the value for weather.id_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public void setIdWeather(Integer idWeather) {
        this.idWeather = idWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.cod_weather
     *
     * @return the value of weather.cod_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public String getCodWeather() {
        return codWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public Weather withCodWeather(String codWeather) {
        this.setCodWeather(codWeather);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.cod_weather
     *
     * @param codWeather the value for weather.cod_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public void setCodWeather(String codWeather) {
        this.codWeather = codWeather == null ? null : codWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.description_weather
     *
     * @return the value of weather.description_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public String getDescriptionWeather() {
        return descriptionWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public Weather withDescriptionWeather(String descriptionWeather) {
        this.setDescriptionWeather(descriptionWeather);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.description_weather
     *
     * @param descriptionWeather the value for weather.description_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public void setDescriptionWeather(String descriptionWeather) {
        this.descriptionWeather = descriptionWeather == null ? null : descriptionWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.img_weather
     *
     * @return the value of weather.img_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public byte[] getImgWeather() {
        return imgWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public Weather withImgWeather(byte[] imgWeather) {
        this.setImgWeather(imgWeather);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.img_weather
     *
     * @param imgWeather the value for weather.img_weather
     *
     * @mbg.generated Sat May 11 19:47:05 CEST 2019
     */
    public void setImgWeather(byte[] imgWeather) {
        this.imgWeather = imgWeather;
    }
}